package com.sh3h.dataprovider.greendaoDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sh3h.dataprovider.data.entity.response.CLJG;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CLJG".
*/
public class CLJGDao extends AbstractDao<CLJG, Void> {

    public static final String TABLENAME = "CLJG";

    /**
     * Properties of entity CLJG.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property CLJG_ID = new Property(0, String.class, "CLJG_ID", false, "CLJG__ID");
        public final static Property DESCR = new Property(1, String.class, "DESCR", false, "DESCR");
    }


    public CLJGDao(DaoConfig config) {
        super(config);
    }
    
    public CLJGDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CLJG\" (" + //
                "\"CLJG__ID\" TEXT," + // 0: CLJG_ID
                "\"DESCR\" TEXT);"); // 1: DESCR
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CLJG\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CLJG entity) {
        stmt.clearBindings();
 
        String CLJG_ID = entity.getCLJG_ID();
        if (CLJG_ID != null) {
            stmt.bindString(1, CLJG_ID);
        }
 
        String DESCR = entity.getDESCR();
        if (DESCR != null) {
            stmt.bindString(2, DESCR);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CLJG entity) {
        stmt.clearBindings();
 
        String CLJG_ID = entity.getCLJG_ID();
        if (CLJG_ID != null) {
            stmt.bindString(1, CLJG_ID);
        }
 
        String DESCR = entity.getDESCR();
        if (DESCR != null) {
            stmt.bindString(2, DESCR);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public CLJG readEntity(Cursor cursor, int offset) {
        CLJG entity = new CLJG( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // CLJG_ID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // DESCR
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CLJG entity, int offset) {
        entity.setCLJG_ID(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setDESCR(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(CLJG entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(CLJG entity) {
        return null;
    }

    @Override
    public boolean hasKey(CLJG entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
