package com.sh3h.dataprovider.greendaoDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sh3h.dataprovider.data.entity.newentity.CollectionHandleEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COLLECTION_HANDLE_ENTITY".
*/
public class CollectionHandleEntityDao extends AbstractDao<CollectionHandleEntity, Long> {

    public static final String TABLENAME = "COLLECTION_HANDLE_ENTITY";

    /**
     * Properties of entity CollectionHandleEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ID = new Property(0, Long.class, "ID", true, "_id");
        public final static Property Albh = new Property(1, String.class, "albh", false, "ALBH");
        public final static Property Pch = new Property(2, String.class, "pch", false, "PCH");
        public final static Property Xh = new Property(3, String.class, "xh", false, "XH");
        public final static Property Yhh = new Property(4, String.class, "yhh", false, "YHH");
        public final static Property Zhbh = new Property(5, String.class, "zhbh", false, "ZHBH");
        public final static Property Cjjg = new Property(6, String.class, "cjjg", false, "CJJG");
        public final static Property Cjbz = new Property(7, String.class, "cjbz", false, "CJBZ");
        public final static Property Xxbg = new Property(8, String.class, "xxbg", false, "XXBG");
        public final static Property Lxr = new Property(9, String.class, "lxr", false, "LXR");
        public final static Property Lxfs = new Property(10, String.class, "lxfs", false, "LXFS");
    }


    public CollectionHandleEntityDao(DaoConfig config) {
        super(config);
    }
    
    public CollectionHandleEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COLLECTION_HANDLE_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: ID
                "\"ALBH\" TEXT," + // 1: albh
                "\"PCH\" TEXT," + // 2: pch
                "\"XH\" TEXT," + // 3: xh
                "\"YHH\" TEXT," + // 4: yhh
                "\"ZHBH\" TEXT," + // 5: zhbh
                "\"CJJG\" TEXT," + // 6: cjjg
                "\"CJBZ\" TEXT," + // 7: cjbz
                "\"XXBG\" TEXT," + // 8: xxbg
                "\"LXR\" TEXT," + // 9: lxr
                "\"LXFS\" TEXT);"); // 10: lxfs
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COLLECTION_HANDLE_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CollectionHandleEntity entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
 
        String albh = entity.getAlbh();
        if (albh != null) {
            stmt.bindString(2, albh);
        }
 
        String pch = entity.getPch();
        if (pch != null) {
            stmt.bindString(3, pch);
        }
 
        String xh = entity.getXh();
        if (xh != null) {
            stmt.bindString(4, xh);
        }
 
        String yhh = entity.getYhh();
        if (yhh != null) {
            stmt.bindString(5, yhh);
        }
 
        String zhbh = entity.getZhbh();
        if (zhbh != null) {
            stmt.bindString(6, zhbh);
        }
 
        String cjjg = entity.getCjjg();
        if (cjjg != null) {
            stmt.bindString(7, cjjg);
        }
 
        String cjbz = entity.getCjbz();
        if (cjbz != null) {
            stmt.bindString(8, cjbz);
        }
 
        String xxbg = entity.getXxbg();
        if (xxbg != null) {
            stmt.bindString(9, xxbg);
        }
 
        String lxr = entity.getLxr();
        if (lxr != null) {
            stmt.bindString(10, lxr);
        }
 
        String lxfs = entity.getLxfs();
        if (lxfs != null) {
            stmt.bindString(11, lxfs);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CollectionHandleEntity entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
 
        String albh = entity.getAlbh();
        if (albh != null) {
            stmt.bindString(2, albh);
        }
 
        String pch = entity.getPch();
        if (pch != null) {
            stmt.bindString(3, pch);
        }
 
        String xh = entity.getXh();
        if (xh != null) {
            stmt.bindString(4, xh);
        }
 
        String yhh = entity.getYhh();
        if (yhh != null) {
            stmt.bindString(5, yhh);
        }
 
        String zhbh = entity.getZhbh();
        if (zhbh != null) {
            stmt.bindString(6, zhbh);
        }
 
        String cjjg = entity.getCjjg();
        if (cjjg != null) {
            stmt.bindString(7, cjjg);
        }
 
        String cjbz = entity.getCjbz();
        if (cjbz != null) {
            stmt.bindString(8, cjbz);
        }
 
        String xxbg = entity.getXxbg();
        if (xxbg != null) {
            stmt.bindString(9, xxbg);
        }
 
        String lxr = entity.getLxr();
        if (lxr != null) {
            stmt.bindString(10, lxr);
        }
 
        String lxfs = entity.getLxfs();
        if (lxfs != null) {
            stmt.bindString(11, lxfs);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CollectionHandleEntity readEntity(Cursor cursor, int offset) {
        CollectionHandleEntity entity = new CollectionHandleEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // ID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // albh
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // pch
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // xh
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // yhh
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // zhbh
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // cjjg
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // cjbz
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // xxbg
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // lxr
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // lxfs
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CollectionHandleEntity entity, int offset) {
        entity.setID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAlbh(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPch(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setXh(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setYhh(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setZhbh(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCjjg(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setCjbz(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setXxbg(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setLxr(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setLxfs(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CollectionHandleEntity entity, long rowId) {
        entity.setID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CollectionHandleEntity entity) {
        if(entity != null) {
            return entity.getID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CollectionHandleEntity entity) {
        return entity.getID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
