package com.sh3h.dataprovider.greendaoDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sh3h.dataprovider.data.entity.newentity.ArriveDataEntity;
import com.sh3h.dataprovider.data.entity.newentity.CollectionHandleEntity;
import com.sh3h.dataprovider.data.entity.newentity.HandleOrderEntity;
import com.sh3h.dataprovider.data.entity.newentity.IllegalHandleEntity;
import com.sh3h.dataprovider.data.entity.newentity.OverrateCallHandleEntity;
import com.sh3h.dataprovider.data.entity.newentity.OverrateReceiptHandleEntity;
import com.sh3h.dataprovider.data.entity.newentity.OverrateSelfHandleEntity;
import com.sh3h.dataprovider.data.entity.newentity.QuestionHandleEntity;
import com.sh3h.dataprovider.data.entity.newentity.RemoteHandleEntity;
import com.sh3h.dataprovider.data.entity.push.AuditResultsSynchronizationEntity;
import com.sh3h.dataprovider.data.entity.push.ReassignmentSynchronizationEntity;
import com.sh3h.dataprovider.data.entity.push.WorkInfoSynchronizationEntity;
import com.sh3h.dataprovider.data.entity.response.CLJBBean;
import com.sh3h.dataprovider.data.entity.response.CLJG;
import com.sh3h.dataprovider.data.entity.response.DUMyTask;
import com.sh3h.dataprovider.data.entity.response.FSYY;
import com.sh3h.dataprovider.data.entity.response.FYLXBean;
import com.sh3h.dataprovider.data.entity.response.FYLYBean;
import com.sh3h.dataprovider.data.entity.response.FYNRBean;
import com.sh3h.dataprovider.data.entity.response.JJCS;
import com.sh3h.dataprovider.data.entity.response.MRMEMO;
import com.sh3h.dataprovider.data.entity.response.MRSTATUS;
import com.sh3h.dataprovider.data.entity.response.XBBX;
import com.sh3h.dataprovider.greendao.Init;

import com.sh3h.dataprovider.greendaoDao.ArriveDataEntityDao;
import com.sh3h.dataprovider.greendaoDao.CollectionHandleEntityDao;
import com.sh3h.dataprovider.greendaoDao.HandleOrderEntityDao;
import com.sh3h.dataprovider.greendaoDao.IllegalHandleEntityDao;
import com.sh3h.dataprovider.greendaoDao.OverrateCallHandleEntityDao;
import com.sh3h.dataprovider.greendaoDao.OverrateReceiptHandleEntityDao;
import com.sh3h.dataprovider.greendaoDao.OverrateSelfHandleEntityDao;
import com.sh3h.dataprovider.greendaoDao.QuestionHandleEntityDao;
import com.sh3h.dataprovider.greendaoDao.RemoteHandleEntityDao;
import com.sh3h.dataprovider.greendaoDao.AuditResultsSynchronizationEntityDao;
import com.sh3h.dataprovider.greendaoDao.ReassignmentSynchronizationEntityDao;
import com.sh3h.dataprovider.greendaoDao.WorkInfoSynchronizationEntityDao;
import com.sh3h.dataprovider.greendaoDao.CLJBBeanDao;
import com.sh3h.dataprovider.greendaoDao.CLJGDao;
import com.sh3h.dataprovider.greendaoDao.DUMyTaskDao;
import com.sh3h.dataprovider.greendaoDao.FSYYDao;
import com.sh3h.dataprovider.greendaoDao.FYLXBeanDao;
import com.sh3h.dataprovider.greendaoDao.FYLYBeanDao;
import com.sh3h.dataprovider.greendaoDao.FYNRBeanDao;
import com.sh3h.dataprovider.greendaoDao.JJCSDao;
import com.sh3h.dataprovider.greendaoDao.MRMEMODao;
import com.sh3h.dataprovider.greendaoDao.MRSTATUSDao;
import com.sh3h.dataprovider.greendaoDao.XBBXDao;
import com.sh3h.dataprovider.greendaoDao.InitDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig arriveDataEntityDaoConfig;
    private final DaoConfig collectionHandleEntityDaoConfig;
    private final DaoConfig handleOrderEntityDaoConfig;
    private final DaoConfig illegalHandleEntityDaoConfig;
    private final DaoConfig overrateCallHandleEntityDaoConfig;
    private final DaoConfig overrateReceiptHandleEntityDaoConfig;
    private final DaoConfig overrateSelfHandleEntityDaoConfig;
    private final DaoConfig questionHandleEntityDaoConfig;
    private final DaoConfig remoteHandleEntityDaoConfig;
    private final DaoConfig auditResultsSynchronizationEntityDaoConfig;
    private final DaoConfig reassignmentSynchronizationEntityDaoConfig;
    private final DaoConfig workInfoSynchronizationEntityDaoConfig;
    private final DaoConfig cLJBBeanDaoConfig;
    private final DaoConfig cLJGDaoConfig;
    private final DaoConfig dUMyTaskDaoConfig;
    private final DaoConfig fSYYDaoConfig;
    private final DaoConfig fYLXBeanDaoConfig;
    private final DaoConfig fYLYBeanDaoConfig;
    private final DaoConfig fYNRBeanDaoConfig;
    private final DaoConfig jJCSDaoConfig;
    private final DaoConfig mRMEMODaoConfig;
    private final DaoConfig mRSTATUSDaoConfig;
    private final DaoConfig xBBXDaoConfig;
    private final DaoConfig initDaoConfig;

    private final ArriveDataEntityDao arriveDataEntityDao;
    private final CollectionHandleEntityDao collectionHandleEntityDao;
    private final HandleOrderEntityDao handleOrderEntityDao;
    private final IllegalHandleEntityDao illegalHandleEntityDao;
    private final OverrateCallHandleEntityDao overrateCallHandleEntityDao;
    private final OverrateReceiptHandleEntityDao overrateReceiptHandleEntityDao;
    private final OverrateSelfHandleEntityDao overrateSelfHandleEntityDao;
    private final QuestionHandleEntityDao questionHandleEntityDao;
    private final RemoteHandleEntityDao remoteHandleEntityDao;
    private final AuditResultsSynchronizationEntityDao auditResultsSynchronizationEntityDao;
    private final ReassignmentSynchronizationEntityDao reassignmentSynchronizationEntityDao;
    private final WorkInfoSynchronizationEntityDao workInfoSynchronizationEntityDao;
    private final CLJBBeanDao cLJBBeanDao;
    private final CLJGDao cLJGDao;
    private final DUMyTaskDao dUMyTaskDao;
    private final FSYYDao fSYYDao;
    private final FYLXBeanDao fYLXBeanDao;
    private final FYLYBeanDao fYLYBeanDao;
    private final FYNRBeanDao fYNRBeanDao;
    private final JJCSDao jJCSDao;
    private final MRMEMODao mRMEMODao;
    private final MRSTATUSDao mRSTATUSDao;
    private final XBBXDao xBBXDao;
    private final InitDao initDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        arriveDataEntityDaoConfig = daoConfigMap.get(ArriveDataEntityDao.class).clone();
        arriveDataEntityDaoConfig.initIdentityScope(type);

        collectionHandleEntityDaoConfig = daoConfigMap.get(CollectionHandleEntityDao.class).clone();
        collectionHandleEntityDaoConfig.initIdentityScope(type);

        handleOrderEntityDaoConfig = daoConfigMap.get(HandleOrderEntityDao.class).clone();
        handleOrderEntityDaoConfig.initIdentityScope(type);

        illegalHandleEntityDaoConfig = daoConfigMap.get(IllegalHandleEntityDao.class).clone();
        illegalHandleEntityDaoConfig.initIdentityScope(type);

        overrateCallHandleEntityDaoConfig = daoConfigMap.get(OverrateCallHandleEntityDao.class).clone();
        overrateCallHandleEntityDaoConfig.initIdentityScope(type);

        overrateReceiptHandleEntityDaoConfig = daoConfigMap.get(OverrateReceiptHandleEntityDao.class).clone();
        overrateReceiptHandleEntityDaoConfig.initIdentityScope(type);

        overrateSelfHandleEntityDaoConfig = daoConfigMap.get(OverrateSelfHandleEntityDao.class).clone();
        overrateSelfHandleEntityDaoConfig.initIdentityScope(type);

        questionHandleEntityDaoConfig = daoConfigMap.get(QuestionHandleEntityDao.class).clone();
        questionHandleEntityDaoConfig.initIdentityScope(type);

        remoteHandleEntityDaoConfig = daoConfigMap.get(RemoteHandleEntityDao.class).clone();
        remoteHandleEntityDaoConfig.initIdentityScope(type);

        auditResultsSynchronizationEntityDaoConfig = daoConfigMap.get(AuditResultsSynchronizationEntityDao.class).clone();
        auditResultsSynchronizationEntityDaoConfig.initIdentityScope(type);

        reassignmentSynchronizationEntityDaoConfig = daoConfigMap.get(ReassignmentSynchronizationEntityDao.class).clone();
        reassignmentSynchronizationEntityDaoConfig.initIdentityScope(type);

        workInfoSynchronizationEntityDaoConfig = daoConfigMap.get(WorkInfoSynchronizationEntityDao.class).clone();
        workInfoSynchronizationEntityDaoConfig.initIdentityScope(type);

        cLJBBeanDaoConfig = daoConfigMap.get(CLJBBeanDao.class).clone();
        cLJBBeanDaoConfig.initIdentityScope(type);

        cLJGDaoConfig = daoConfigMap.get(CLJGDao.class).clone();
        cLJGDaoConfig.initIdentityScope(type);

        dUMyTaskDaoConfig = daoConfigMap.get(DUMyTaskDao.class).clone();
        dUMyTaskDaoConfig.initIdentityScope(type);

        fSYYDaoConfig = daoConfigMap.get(FSYYDao.class).clone();
        fSYYDaoConfig.initIdentityScope(type);

        fYLXBeanDaoConfig = daoConfigMap.get(FYLXBeanDao.class).clone();
        fYLXBeanDaoConfig.initIdentityScope(type);

        fYLYBeanDaoConfig = daoConfigMap.get(FYLYBeanDao.class).clone();
        fYLYBeanDaoConfig.initIdentityScope(type);

        fYNRBeanDaoConfig = daoConfigMap.get(FYNRBeanDao.class).clone();
        fYNRBeanDaoConfig.initIdentityScope(type);

        jJCSDaoConfig = daoConfigMap.get(JJCSDao.class).clone();
        jJCSDaoConfig.initIdentityScope(type);

        mRMEMODaoConfig = daoConfigMap.get(MRMEMODao.class).clone();
        mRMEMODaoConfig.initIdentityScope(type);

        mRSTATUSDaoConfig = daoConfigMap.get(MRSTATUSDao.class).clone();
        mRSTATUSDaoConfig.initIdentityScope(type);

        xBBXDaoConfig = daoConfigMap.get(XBBXDao.class).clone();
        xBBXDaoConfig.initIdentityScope(type);

        initDaoConfig = daoConfigMap.get(InitDao.class).clone();
        initDaoConfig.initIdentityScope(type);

        arriveDataEntityDao = new ArriveDataEntityDao(arriveDataEntityDaoConfig, this);
        collectionHandleEntityDao = new CollectionHandleEntityDao(collectionHandleEntityDaoConfig, this);
        handleOrderEntityDao = new HandleOrderEntityDao(handleOrderEntityDaoConfig, this);
        illegalHandleEntityDao = new IllegalHandleEntityDao(illegalHandleEntityDaoConfig, this);
        overrateCallHandleEntityDao = new OverrateCallHandleEntityDao(overrateCallHandleEntityDaoConfig, this);
        overrateReceiptHandleEntityDao = new OverrateReceiptHandleEntityDao(overrateReceiptHandleEntityDaoConfig, this);
        overrateSelfHandleEntityDao = new OverrateSelfHandleEntityDao(overrateSelfHandleEntityDaoConfig, this);
        questionHandleEntityDao = new QuestionHandleEntityDao(questionHandleEntityDaoConfig, this);
        remoteHandleEntityDao = new RemoteHandleEntityDao(remoteHandleEntityDaoConfig, this);
        auditResultsSynchronizationEntityDao = new AuditResultsSynchronizationEntityDao(auditResultsSynchronizationEntityDaoConfig, this);
        reassignmentSynchronizationEntityDao = new ReassignmentSynchronizationEntityDao(reassignmentSynchronizationEntityDaoConfig, this);
        workInfoSynchronizationEntityDao = new WorkInfoSynchronizationEntityDao(workInfoSynchronizationEntityDaoConfig, this);
        cLJBBeanDao = new CLJBBeanDao(cLJBBeanDaoConfig, this);
        cLJGDao = new CLJGDao(cLJGDaoConfig, this);
        dUMyTaskDao = new DUMyTaskDao(dUMyTaskDaoConfig, this);
        fSYYDao = new FSYYDao(fSYYDaoConfig, this);
        fYLXBeanDao = new FYLXBeanDao(fYLXBeanDaoConfig, this);
        fYLYBeanDao = new FYLYBeanDao(fYLYBeanDaoConfig, this);
        fYNRBeanDao = new FYNRBeanDao(fYNRBeanDaoConfig, this);
        jJCSDao = new JJCSDao(jJCSDaoConfig, this);
        mRMEMODao = new MRMEMODao(mRMEMODaoConfig, this);
        mRSTATUSDao = new MRSTATUSDao(mRSTATUSDaoConfig, this);
        xBBXDao = new XBBXDao(xBBXDaoConfig, this);
        initDao = new InitDao(initDaoConfig, this);

        registerDao(ArriveDataEntity.class, arriveDataEntityDao);
        registerDao(CollectionHandleEntity.class, collectionHandleEntityDao);
        registerDao(HandleOrderEntity.class, handleOrderEntityDao);
        registerDao(IllegalHandleEntity.class, illegalHandleEntityDao);
        registerDao(OverrateCallHandleEntity.class, overrateCallHandleEntityDao);
        registerDao(OverrateReceiptHandleEntity.class, overrateReceiptHandleEntityDao);
        registerDao(OverrateSelfHandleEntity.class, overrateSelfHandleEntityDao);
        registerDao(QuestionHandleEntity.class, questionHandleEntityDao);
        registerDao(RemoteHandleEntity.class, remoteHandleEntityDao);
        registerDao(AuditResultsSynchronizationEntity.class, auditResultsSynchronizationEntityDao);
        registerDao(ReassignmentSynchronizationEntity.class, reassignmentSynchronizationEntityDao);
        registerDao(WorkInfoSynchronizationEntity.class, workInfoSynchronizationEntityDao);
        registerDao(CLJBBean.class, cLJBBeanDao);
        registerDao(CLJG.class, cLJGDao);
        registerDao(DUMyTask.class, dUMyTaskDao);
        registerDao(FSYY.class, fSYYDao);
        registerDao(FYLXBean.class, fYLXBeanDao);
        registerDao(FYLYBean.class, fYLYBeanDao);
        registerDao(FYNRBean.class, fYNRBeanDao);
        registerDao(JJCS.class, jJCSDao);
        registerDao(MRMEMO.class, mRMEMODao);
        registerDao(MRSTATUS.class, mRSTATUSDao);
        registerDao(XBBX.class, xBBXDao);
        registerDao(Init.class, initDao);
    }
    
    public void clear() {
        arriveDataEntityDaoConfig.clearIdentityScope();
        collectionHandleEntityDaoConfig.clearIdentityScope();
        handleOrderEntityDaoConfig.clearIdentityScope();
        illegalHandleEntityDaoConfig.clearIdentityScope();
        overrateCallHandleEntityDaoConfig.clearIdentityScope();
        overrateReceiptHandleEntityDaoConfig.clearIdentityScope();
        overrateSelfHandleEntityDaoConfig.clearIdentityScope();
        questionHandleEntityDaoConfig.clearIdentityScope();
        remoteHandleEntityDaoConfig.clearIdentityScope();
        auditResultsSynchronizationEntityDaoConfig.clearIdentityScope();
        reassignmentSynchronizationEntityDaoConfig.clearIdentityScope();
        workInfoSynchronizationEntityDaoConfig.clearIdentityScope();
        cLJBBeanDaoConfig.clearIdentityScope();
        cLJGDaoConfig.clearIdentityScope();
        dUMyTaskDaoConfig.clearIdentityScope();
        fSYYDaoConfig.clearIdentityScope();
        fYLXBeanDaoConfig.clearIdentityScope();
        fYLYBeanDaoConfig.clearIdentityScope();
        fYNRBeanDaoConfig.clearIdentityScope();
        jJCSDaoConfig.clearIdentityScope();
        mRMEMODaoConfig.clearIdentityScope();
        mRSTATUSDaoConfig.clearIdentityScope();
        xBBXDaoConfig.clearIdentityScope();
        initDaoConfig.clearIdentityScope();
    }

    public ArriveDataEntityDao getArriveDataEntityDao() {
        return arriveDataEntityDao;
    }

    public CollectionHandleEntityDao getCollectionHandleEntityDao() {
        return collectionHandleEntityDao;
    }

    public HandleOrderEntityDao getHandleOrderEntityDao() {
        return handleOrderEntityDao;
    }

    public IllegalHandleEntityDao getIllegalHandleEntityDao() {
        return illegalHandleEntityDao;
    }

    public OverrateCallHandleEntityDao getOverrateCallHandleEntityDao() {
        return overrateCallHandleEntityDao;
    }

    public OverrateReceiptHandleEntityDao getOverrateReceiptHandleEntityDao() {
        return overrateReceiptHandleEntityDao;
    }

    public OverrateSelfHandleEntityDao getOverrateSelfHandleEntityDao() {
        return overrateSelfHandleEntityDao;
    }

    public QuestionHandleEntityDao getQuestionHandleEntityDao() {
        return questionHandleEntityDao;
    }

    public RemoteHandleEntityDao getRemoteHandleEntityDao() {
        return remoteHandleEntityDao;
    }

    public AuditResultsSynchronizationEntityDao getAuditResultsSynchronizationEntityDao() {
        return auditResultsSynchronizationEntityDao;
    }

    public ReassignmentSynchronizationEntityDao getReassignmentSynchronizationEntityDao() {
        return reassignmentSynchronizationEntityDao;
    }

    public WorkInfoSynchronizationEntityDao getWorkInfoSynchronizationEntityDao() {
        return workInfoSynchronizationEntityDao;
    }

    public CLJBBeanDao getCLJBBeanDao() {
        return cLJBBeanDao;
    }

    public CLJGDao getCLJGDao() {
        return cLJGDao;
    }

    public DUMyTaskDao getDUMyTaskDao() {
        return dUMyTaskDao;
    }

    public FSYYDao getFSYYDao() {
        return fSYYDao;
    }

    public FYLXBeanDao getFYLXBeanDao() {
        return fYLXBeanDao;
    }

    public FYLYBeanDao getFYLYBeanDao() {
        return fYLYBeanDao;
    }

    public FYNRBeanDao getFYNRBeanDao() {
        return fYNRBeanDao;
    }

    public JJCSDao getJJCSDao() {
        return jJCSDao;
    }

    public MRMEMODao getMRMEMODao() {
        return mRMEMODao;
    }

    public MRSTATUSDao getMRSTATUSDao() {
        return mRSTATUSDao;
    }

    public XBBXDao getXBBXDao() {
        return xBBXDao;
    }

    public InitDao getInitDao() {
        return initDao;
    }

}
