package com.sh3h.dataprovider.greendaoDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sh3h.dataprovider.data.entity.response.FYLXBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FYLXBEAN".
*/
public class FYLXBeanDao extends AbstractDao<FYLXBean, Void> {

    public static final String TABLENAME = "FYLXBEAN";

    /**
     * Properties of entity FYLXBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property LB_ID = new Property(0, String.class, "LB_ID", false, "LB__ID");
        public final static Property FA_TYPE_CD = new Property(1, String.class, "FA_TYPE_CD", false, "FA__TYPE__CD");
        public final static Property FA_TYPE_DESCR = new Property(2, String.class, "FA_TYPE_DESCR", false, "FA__TYPE__DESCR");
        public final static Property BUS_TYPE = new Property(3, String.class, "BUS_TYPE", false, "BUS__TYPE");
    }


    public FYLXBeanDao(DaoConfig config) {
        super(config);
    }
    
    public FYLXBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FYLXBEAN\" (" + //
                "\"LB__ID\" TEXT," + // 0: LB_ID
                "\"FA__TYPE__CD\" TEXT," + // 1: FA_TYPE_CD
                "\"FA__TYPE__DESCR\" TEXT," + // 2: FA_TYPE_DESCR
                "\"BUS__TYPE\" TEXT);"); // 3: BUS_TYPE
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FYLXBEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FYLXBean entity) {
        stmt.clearBindings();
 
        String LB_ID = entity.getLB_ID();
        if (LB_ID != null) {
            stmt.bindString(1, LB_ID);
        }
 
        String FA_TYPE_CD = entity.getFA_TYPE_CD();
        if (FA_TYPE_CD != null) {
            stmt.bindString(2, FA_TYPE_CD);
        }
 
        String FA_TYPE_DESCR = entity.getFA_TYPE_DESCR();
        if (FA_TYPE_DESCR != null) {
            stmt.bindString(3, FA_TYPE_DESCR);
        }
 
        String BUS_TYPE = entity.getBUS_TYPE();
        if (BUS_TYPE != null) {
            stmt.bindString(4, BUS_TYPE);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FYLXBean entity) {
        stmt.clearBindings();
 
        String LB_ID = entity.getLB_ID();
        if (LB_ID != null) {
            stmt.bindString(1, LB_ID);
        }
 
        String FA_TYPE_CD = entity.getFA_TYPE_CD();
        if (FA_TYPE_CD != null) {
            stmt.bindString(2, FA_TYPE_CD);
        }
 
        String FA_TYPE_DESCR = entity.getFA_TYPE_DESCR();
        if (FA_TYPE_DESCR != null) {
            stmt.bindString(3, FA_TYPE_DESCR);
        }
 
        String BUS_TYPE = entity.getBUS_TYPE();
        if (BUS_TYPE != null) {
            stmt.bindString(4, BUS_TYPE);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public FYLXBean readEntity(Cursor cursor, int offset) {
        FYLXBean entity = new FYLXBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // LB_ID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // FA_TYPE_CD
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // FA_TYPE_DESCR
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // BUS_TYPE
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FYLXBean entity, int offset) {
        entity.setLB_ID(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setFA_TYPE_CD(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setFA_TYPE_DESCR(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBUS_TYPE(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(FYLXBean entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(FYLXBean entity) {
        return null;
    }

    @Override
    public boolean hasKey(FYLXBean entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
