package com.sh3h.dataprovider.greendaoDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sh3h.dataprovider.greendao.Init;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "INIT".
*/
public class InitDao extends AbstractDao<Init, Void> {

    public static final String TABLENAME = "INIT";

    /**
     * Properties of entity Init.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property TestGreendao = new Property(0, String.class, "testGreendao", false, "TEST_GREENDAO");
    }


    public InitDao(DaoConfig config) {
        super(config);
    }
    
    public InitDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"INIT\" (" + //
                "\"TEST_GREENDAO\" TEXT);"); // 0: testGreendao
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"INIT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Init entity) {
        stmt.clearBindings();
 
        String testGreendao = entity.getTestGreendao();
        if (testGreendao != null) {
            stmt.bindString(1, testGreendao);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Init entity) {
        stmt.clearBindings();
 
        String testGreendao = entity.getTestGreendao();
        if (testGreendao != null) {
            stmt.bindString(1, testGreendao);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public Init readEntity(Cursor cursor, int offset) {
        Init entity = new Init( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // testGreendao
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Init entity, int offset) {
        entity.setTestGreendao(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(Init entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(Init entity) {
        return null;
    }

    @Override
    public boolean hasKey(Init entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
