package com.sh3h.dataprovider.greendaoDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sh3h.dataprovider.data.entity.newentity.OverrateReceiptHandleEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "OVERRATE_RECEIPT_HANDLE_ENTITY".
*/
public class OverrateReceiptHandleEntityDao extends AbstractDao<OverrateReceiptHandleEntity, Long> {

    public static final String TABLENAME = "OVERRATE_RECEIPT_HANDLE_ENTITY";

    /**
     * Properties of entity OverrateReceiptHandleEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ID = new Property(0, Long.class, "ID", true, "_id");
        public final static Property Albh = new Property(1, String.class, "albh", false, "ALBH");
        public final static Property Pch = new Property(2, String.class, "pch", false, "PCH");
        public final static Property Xh = new Property(3, String.class, "xh", false, "XH");
        public final static Property Yhh = new Property(4, String.class, "yhh", false, "YHH");
        public final static Property Psfs = new Property(5, String.class, "psfs", false, "PSFS");
        public final static Property Ghxdh = new Property(6, String.class, "ghxdh", false, "GHXDH");
        public final static Property Sfsd = new Property(7, String.class, "sfsd", false, "SFSD");
        public final static Property Wqsyy = new Property(8, String.class, "wqsyy", false, "WQSYY");
        public final static Property Qsr = new Property(9, String.class, "qsr", false, "QSR");
        public final static Property Sjrsf = new Property(10, String.class, "sjrsf", false, "SJRSF");
        public final static Property Fdqkbz = new Property(11, String.class, "fdqkbz", false, "FDQKBZ");
        public final static Property Xxbg = new Property(12, String.class, "xxbg", false, "XXBG");
        public final static Property Zhbh = new Property(13, String.class, "zhbh", false, "ZHBH");
        public final static Property Xzq = new Property(14, String.class, "xzq", false, "XZQ");
        public final static Property Ssdm = new Property(15, String.class, "ssdm", false, "SSDM");
        public final static Property Khlx = new Property(16, String.class, "khlx", false, "KHLX");
        public final static Property Tyshxydm = new Property(17, String.class, "tyshxydm", false, "TYSHXYDM");
        public final static Property Khmc = new Property(18, String.class, "khmc", false, "KHMC");
        public final static Property Lxr = new Property(19, String.class, "lxr", false, "LXR");
        public final static Property Lxfs = new Property(20, String.class, "lxfs", false, "LXFS");
        public final static Property Yjdz = new Property(21, String.class, "yjdz", false, "YJDZ");
        public final static Property Bz = new Property(22, String.class, "bz", false, "BZ");
        public final static Property Youbian = new Property(23, String.class, "youbian", false, "YOUBIAN");
        public final static Property QsrTel = new Property(24, String.class, "qsrTel", false, "QSR_TEL");
    }


    public OverrateReceiptHandleEntityDao(DaoConfig config) {
        super(config);
    }
    
    public OverrateReceiptHandleEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"OVERRATE_RECEIPT_HANDLE_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: ID
                "\"ALBH\" TEXT," + // 1: albh
                "\"PCH\" TEXT," + // 2: pch
                "\"XH\" TEXT," + // 3: xh
                "\"YHH\" TEXT," + // 4: yhh
                "\"PSFS\" TEXT," + // 5: psfs
                "\"GHXDH\" TEXT," + // 6: ghxdh
                "\"SFSD\" TEXT," + // 7: sfsd
                "\"WQSYY\" TEXT," + // 8: wqsyy
                "\"QSR\" TEXT," + // 9: qsr
                "\"SJRSF\" TEXT," + // 10: sjrsf
                "\"FDQKBZ\" TEXT," + // 11: fdqkbz
                "\"XXBG\" TEXT," + // 12: xxbg
                "\"ZHBH\" TEXT," + // 13: zhbh
                "\"XZQ\" TEXT," + // 14: xzq
                "\"SSDM\" TEXT," + // 15: ssdm
                "\"KHLX\" TEXT," + // 16: khlx
                "\"TYSHXYDM\" TEXT," + // 17: tyshxydm
                "\"KHMC\" TEXT," + // 18: khmc
                "\"LXR\" TEXT," + // 19: lxr
                "\"LXFS\" TEXT," + // 20: lxfs
                "\"YJDZ\" TEXT," + // 21: yjdz
                "\"BZ\" TEXT," + // 22: bz
                "\"YOUBIAN\" TEXT," + // 23: youbian
                "\"QSR_TEL\" TEXT);"); // 24: qsrTel
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"OVERRATE_RECEIPT_HANDLE_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, OverrateReceiptHandleEntity entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
 
        String albh = entity.getAlbh();
        if (albh != null) {
            stmt.bindString(2, albh);
        }
 
        String pch = entity.getPch();
        if (pch != null) {
            stmt.bindString(3, pch);
        }
 
        String xh = entity.getXh();
        if (xh != null) {
            stmt.bindString(4, xh);
        }
 
        String yhh = entity.getYhh();
        if (yhh != null) {
            stmt.bindString(5, yhh);
        }
 
        String psfs = entity.getPsfs();
        if (psfs != null) {
            stmt.bindString(6, psfs);
        }
 
        String ghxdh = entity.getGhxdh();
        if (ghxdh != null) {
            stmt.bindString(7, ghxdh);
        }
 
        String sfsd = entity.getSfsd();
        if (sfsd != null) {
            stmt.bindString(8, sfsd);
        }
 
        String wqsyy = entity.getWqsyy();
        if (wqsyy != null) {
            stmt.bindString(9, wqsyy);
        }
 
        String qsr = entity.getQsr();
        if (qsr != null) {
            stmt.bindString(10, qsr);
        }
 
        String sjrsf = entity.getSjrsf();
        if (sjrsf != null) {
            stmt.bindString(11, sjrsf);
        }
 
        String fdqkbz = entity.getFdqkbz();
        if (fdqkbz != null) {
            stmt.bindString(12, fdqkbz);
        }
 
        String xxbg = entity.getXxbg();
        if (xxbg != null) {
            stmt.bindString(13, xxbg);
        }
 
        String zhbh = entity.getZhbh();
        if (zhbh != null) {
            stmt.bindString(14, zhbh);
        }
 
        String xzq = entity.getXzq();
        if (xzq != null) {
            stmt.bindString(15, xzq);
        }
 
        String ssdm = entity.getSsdm();
        if (ssdm != null) {
            stmt.bindString(16, ssdm);
        }
 
        String khlx = entity.getKhlx();
        if (khlx != null) {
            stmt.bindString(17, khlx);
        }
 
        String tyshxydm = entity.getTyshxydm();
        if (tyshxydm != null) {
            stmt.bindString(18, tyshxydm);
        }
 
        String khmc = entity.getKhmc();
        if (khmc != null) {
            stmt.bindString(19, khmc);
        }
 
        String lxr = entity.getLxr();
        if (lxr != null) {
            stmt.bindString(20, lxr);
        }
 
        String lxfs = entity.getLxfs();
        if (lxfs != null) {
            stmt.bindString(21, lxfs);
        }
 
        String yjdz = entity.getYjdz();
        if (yjdz != null) {
            stmt.bindString(22, yjdz);
        }
 
        String bz = entity.getBz();
        if (bz != null) {
            stmt.bindString(23, bz);
        }
 
        String youbian = entity.getYoubian();
        if (youbian != null) {
            stmt.bindString(24, youbian);
        }
 
        String qsrTel = entity.getQsrTel();
        if (qsrTel != null) {
            stmt.bindString(25, qsrTel);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, OverrateReceiptHandleEntity entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
 
        String albh = entity.getAlbh();
        if (albh != null) {
            stmt.bindString(2, albh);
        }
 
        String pch = entity.getPch();
        if (pch != null) {
            stmt.bindString(3, pch);
        }
 
        String xh = entity.getXh();
        if (xh != null) {
            stmt.bindString(4, xh);
        }
 
        String yhh = entity.getYhh();
        if (yhh != null) {
            stmt.bindString(5, yhh);
        }
 
        String psfs = entity.getPsfs();
        if (psfs != null) {
            stmt.bindString(6, psfs);
        }
 
        String ghxdh = entity.getGhxdh();
        if (ghxdh != null) {
            stmt.bindString(7, ghxdh);
        }
 
        String sfsd = entity.getSfsd();
        if (sfsd != null) {
            stmt.bindString(8, sfsd);
        }
 
        String wqsyy = entity.getWqsyy();
        if (wqsyy != null) {
            stmt.bindString(9, wqsyy);
        }
 
        String qsr = entity.getQsr();
        if (qsr != null) {
            stmt.bindString(10, qsr);
        }
 
        String sjrsf = entity.getSjrsf();
        if (sjrsf != null) {
            stmt.bindString(11, sjrsf);
        }
 
        String fdqkbz = entity.getFdqkbz();
        if (fdqkbz != null) {
            stmt.bindString(12, fdqkbz);
        }
 
        String xxbg = entity.getXxbg();
        if (xxbg != null) {
            stmt.bindString(13, xxbg);
        }
 
        String zhbh = entity.getZhbh();
        if (zhbh != null) {
            stmt.bindString(14, zhbh);
        }
 
        String xzq = entity.getXzq();
        if (xzq != null) {
            stmt.bindString(15, xzq);
        }
 
        String ssdm = entity.getSsdm();
        if (ssdm != null) {
            stmt.bindString(16, ssdm);
        }
 
        String khlx = entity.getKhlx();
        if (khlx != null) {
            stmt.bindString(17, khlx);
        }
 
        String tyshxydm = entity.getTyshxydm();
        if (tyshxydm != null) {
            stmt.bindString(18, tyshxydm);
        }
 
        String khmc = entity.getKhmc();
        if (khmc != null) {
            stmt.bindString(19, khmc);
        }
 
        String lxr = entity.getLxr();
        if (lxr != null) {
            stmt.bindString(20, lxr);
        }
 
        String lxfs = entity.getLxfs();
        if (lxfs != null) {
            stmt.bindString(21, lxfs);
        }
 
        String yjdz = entity.getYjdz();
        if (yjdz != null) {
            stmt.bindString(22, yjdz);
        }
 
        String bz = entity.getBz();
        if (bz != null) {
            stmt.bindString(23, bz);
        }
 
        String youbian = entity.getYoubian();
        if (youbian != null) {
            stmt.bindString(24, youbian);
        }
 
        String qsrTel = entity.getQsrTel();
        if (qsrTel != null) {
            stmt.bindString(25, qsrTel);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public OverrateReceiptHandleEntity readEntity(Cursor cursor, int offset) {
        OverrateReceiptHandleEntity entity = new OverrateReceiptHandleEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // ID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // albh
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // pch
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // xh
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // yhh
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // psfs
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // ghxdh
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // sfsd
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // wqsyy
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // qsr
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // sjrsf
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // fdqkbz
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // xxbg
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // zhbh
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // xzq
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // ssdm
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // khlx
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // tyshxydm
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // khmc
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // lxr
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // lxfs
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // yjdz
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // bz
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // youbian
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24) // qsrTel
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, OverrateReceiptHandleEntity entity, int offset) {
        entity.setID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAlbh(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPch(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setXh(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setYhh(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPsfs(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setGhxdh(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setSfsd(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setWqsyy(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setQsr(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setSjrsf(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setFdqkbz(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setXxbg(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setZhbh(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setXzq(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setSsdm(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setKhlx(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setTyshxydm(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setKhmc(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setLxr(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setLxfs(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setYjdz(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setBz(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setYoubian(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setQsrTel(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(OverrateReceiptHandleEntity entity, long rowId) {
        entity.setID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(OverrateReceiptHandleEntity entity) {
        if(entity != null) {
            return entity.getID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(OverrateReceiptHandleEntity entity) {
        return entity.getID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
