package com.sh3h.dataprovider.greendaoDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sh3h.dataprovider.data.entity.push.WorkInfoSynchronizationEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WORK_INFO_SYNCHRONIZATION_ENTITY".
*/
public class WorkInfoSynchronizationEntityDao extends AbstractDao<WorkInfoSynchronizationEntity, Void> {

    public static final String TABLENAME = "WORK_INFO_SYNCHRONIZATION_ENTITY";

    /**
     * Properties of entity WorkInfoSynchronizationEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property FaId = new Property(0, String.class, "faId", false, "FA_ID");
        public final static Property CaseId = new Property(1, String.class, "caseId", false, "CASE_ID");
        public final static Property OldCaseId = new Property(2, String.class, "oldCaseId", false, "OLD_CASE_ID");
        public final static Property CmSta = new Property(3, String.class, "cmSta", false, "CM_STA");
        public final static Property EntityName = new Property(4, String.class, "entityName", false, "ENTITY_NAME");
        public final static Property DisPatGrp = new Property(5, String.class, "disPatGrp", false, "DIS_PAT_GRP");
        public final static Property RepCd = new Property(6, String.class, "repCd", false, "REP_CD");
        public final static Property AcctId = new Property(7, String.class, "acctId", false, "ACCT_ID");
        public final static Property Ldsj = new Property(8, String.class, "ldsj", false, "LDSJ");
        public final static Property Fsdz = new Property(9, String.class, "fsdz", false, "FSDZ");
        public final static Property ContactValue = new Property(10, String.class, "contactValue", false, "CONTACT_VALUE");
        public final static Property Mobile = new Property(11, String.class, "mobile", false, "MOBILE");
        public final static Property Fyly = new Property(12, String.class, "fyly", false, "FYLY");
        public final static Property FaTypeCd = new Property(13, String.class, "faTypeCd", false, "FA_TYPE_CD");
        public final static Property Fynr = new Property(14, String.class, "fynr", false, "FYNR");
        public final static Property Cljb = new Property(15, String.class, "cljb", false, "CLJB");
        public final static Property Clsx = new Property(16, String.class, "clsx", false, "CLSX");
        public final static Property Comment = new Property(17, String.class, "comment", false, "COMMENT");
        public final static Property CreDttm = new Property(18, String.class, "creDttm", false, "CRE_DTTM");
    }


    public WorkInfoSynchronizationEntityDao(DaoConfig config) {
        super(config);
    }
    
    public WorkInfoSynchronizationEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WORK_INFO_SYNCHRONIZATION_ENTITY\" (" + //
                "\"FA_ID\" TEXT," + // 0: faId
                "\"CASE_ID\" TEXT," + // 1: caseId
                "\"OLD_CASE_ID\" TEXT," + // 2: oldCaseId
                "\"CM_STA\" TEXT," + // 3: cmSta
                "\"ENTITY_NAME\" TEXT," + // 4: entityName
                "\"DIS_PAT_GRP\" TEXT," + // 5: disPatGrp
                "\"REP_CD\" TEXT," + // 6: repCd
                "\"ACCT_ID\" TEXT," + // 7: acctId
                "\"LDSJ\" TEXT," + // 8: ldsj
                "\"FSDZ\" TEXT," + // 9: fsdz
                "\"CONTACT_VALUE\" TEXT," + // 10: contactValue
                "\"MOBILE\" TEXT," + // 11: mobile
                "\"FYLY\" TEXT," + // 12: fyly
                "\"FA_TYPE_CD\" TEXT," + // 13: faTypeCd
                "\"FYNR\" TEXT," + // 14: fynr
                "\"CLJB\" TEXT," + // 15: cljb
                "\"CLSX\" TEXT," + // 16: clsx
                "\"COMMENT\" TEXT," + // 17: comment
                "\"CRE_DTTM\" TEXT);"); // 18: creDttm
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WORK_INFO_SYNCHRONIZATION_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, WorkInfoSynchronizationEntity entity) {
        stmt.clearBindings();
 
        String faId = entity.getFaId();
        if (faId != null) {
            stmt.bindString(1, faId);
        }
 
        String caseId = entity.getCaseId();
        if (caseId != null) {
            stmt.bindString(2, caseId);
        }
 
        String oldCaseId = entity.getOldCaseId();
        if (oldCaseId != null) {
            stmt.bindString(3, oldCaseId);
        }
 
        String cmSta = entity.getCmSta();
        if (cmSta != null) {
            stmt.bindString(4, cmSta);
        }
 
        String entityName = entity.getEntityName();
        if (entityName != null) {
            stmt.bindString(5, entityName);
        }
 
        String disPatGrp = entity.getDisPatGrp();
        if (disPatGrp != null) {
            stmt.bindString(6, disPatGrp);
        }
 
        String repCd = entity.getRepCd();
        if (repCd != null) {
            stmt.bindString(7, repCd);
        }
 
        String acctId = entity.getAcctId();
        if (acctId != null) {
            stmt.bindString(8, acctId);
        }
 
        String ldsj = entity.getLdsj();
        if (ldsj != null) {
            stmt.bindString(9, ldsj);
        }
 
        String fsdz = entity.getFsdz();
        if (fsdz != null) {
            stmt.bindString(10, fsdz);
        }
 
        String contactValue = entity.getContactValue();
        if (contactValue != null) {
            stmt.bindString(11, contactValue);
        }
 
        String mobile = entity.getMobile();
        if (mobile != null) {
            stmt.bindString(12, mobile);
        }
 
        String fyly = entity.getFyly();
        if (fyly != null) {
            stmt.bindString(13, fyly);
        }
 
        String faTypeCd = entity.getFaTypeCd();
        if (faTypeCd != null) {
            stmt.bindString(14, faTypeCd);
        }
 
        String fynr = entity.getFynr();
        if (fynr != null) {
            stmt.bindString(15, fynr);
        }
 
        String cljb = entity.getCljb();
        if (cljb != null) {
            stmt.bindString(16, cljb);
        }
 
        String clsx = entity.getClsx();
        if (clsx != null) {
            stmt.bindString(17, clsx);
        }
 
        String comment = entity.getComment();
        if (comment != null) {
            stmt.bindString(18, comment);
        }
 
        String creDttm = entity.getCreDttm();
        if (creDttm != null) {
            stmt.bindString(19, creDttm);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, WorkInfoSynchronizationEntity entity) {
        stmt.clearBindings();
 
        String faId = entity.getFaId();
        if (faId != null) {
            stmt.bindString(1, faId);
        }
 
        String caseId = entity.getCaseId();
        if (caseId != null) {
            stmt.bindString(2, caseId);
        }
 
        String oldCaseId = entity.getOldCaseId();
        if (oldCaseId != null) {
            stmt.bindString(3, oldCaseId);
        }
 
        String cmSta = entity.getCmSta();
        if (cmSta != null) {
            stmt.bindString(4, cmSta);
        }
 
        String entityName = entity.getEntityName();
        if (entityName != null) {
            stmt.bindString(5, entityName);
        }
 
        String disPatGrp = entity.getDisPatGrp();
        if (disPatGrp != null) {
            stmt.bindString(6, disPatGrp);
        }
 
        String repCd = entity.getRepCd();
        if (repCd != null) {
            stmt.bindString(7, repCd);
        }
 
        String acctId = entity.getAcctId();
        if (acctId != null) {
            stmt.bindString(8, acctId);
        }
 
        String ldsj = entity.getLdsj();
        if (ldsj != null) {
            stmt.bindString(9, ldsj);
        }
 
        String fsdz = entity.getFsdz();
        if (fsdz != null) {
            stmt.bindString(10, fsdz);
        }
 
        String contactValue = entity.getContactValue();
        if (contactValue != null) {
            stmt.bindString(11, contactValue);
        }
 
        String mobile = entity.getMobile();
        if (mobile != null) {
            stmt.bindString(12, mobile);
        }
 
        String fyly = entity.getFyly();
        if (fyly != null) {
            stmt.bindString(13, fyly);
        }
 
        String faTypeCd = entity.getFaTypeCd();
        if (faTypeCd != null) {
            stmt.bindString(14, faTypeCd);
        }
 
        String fynr = entity.getFynr();
        if (fynr != null) {
            stmt.bindString(15, fynr);
        }
 
        String cljb = entity.getCljb();
        if (cljb != null) {
            stmt.bindString(16, cljb);
        }
 
        String clsx = entity.getClsx();
        if (clsx != null) {
            stmt.bindString(17, clsx);
        }
 
        String comment = entity.getComment();
        if (comment != null) {
            stmt.bindString(18, comment);
        }
 
        String creDttm = entity.getCreDttm();
        if (creDttm != null) {
            stmt.bindString(19, creDttm);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public WorkInfoSynchronizationEntity readEntity(Cursor cursor, int offset) {
        WorkInfoSynchronizationEntity entity = new WorkInfoSynchronizationEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // faId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // caseId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // oldCaseId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // cmSta
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // entityName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // disPatGrp
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // repCd
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // acctId
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // ldsj
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // fsdz
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // contactValue
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // mobile
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // fyly
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // faTypeCd
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // fynr
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // cljb
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // clsx
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // comment
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18) // creDttm
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, WorkInfoSynchronizationEntity entity, int offset) {
        entity.setFaId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setCaseId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setOldCaseId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCmSta(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setEntityName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDisPatGrp(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setRepCd(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setAcctId(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setLdsj(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setFsdz(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setContactValue(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setMobile(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setFyly(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setFaTypeCd(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setFynr(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setCljb(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setClsx(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setComment(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setCreDttm(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(WorkInfoSynchronizationEntity entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(WorkInfoSynchronizationEntity entity) {
        return null;
    }

    @Override
    public boolean hasKey(WorkInfoSynchronizationEntity entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
