package com.sh3h.localprovider.greendaoDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sh3h.localprovider.greendaoEntity.HistoryTask;
import com.sh3h.localprovider.greendaoEntity.MultiMedia;
import com.sh3h.localprovider.greendaoEntity.Task;
import com.sh3h.localprovider.greendaoEntity.Word;

import com.sh3h.localprovider.greendaoDao.HistoryTaskDao;
import com.sh3h.localprovider.greendaoDao.MultiMediaDao;
import com.sh3h.localprovider.greendaoDao.TaskDao;
import com.sh3h.localprovider.greendaoDao.WordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig historyTaskDaoConfig;
    private final DaoConfig multiMediaDaoConfig;
    private final DaoConfig taskDaoConfig;
    private final DaoConfig wordDaoConfig;

    private final HistoryTaskDao historyTaskDao;
    private final MultiMediaDao multiMediaDao;
    private final TaskDao taskDao;
    private final WordDao wordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        historyTaskDaoConfig = daoConfigMap.get(HistoryTaskDao.class).clone();
        historyTaskDaoConfig.initIdentityScope(type);

        multiMediaDaoConfig = daoConfigMap.get(MultiMediaDao.class).clone();
        multiMediaDaoConfig.initIdentityScope(type);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        wordDaoConfig = daoConfigMap.get(WordDao.class).clone();
        wordDaoConfig.initIdentityScope(type);

        historyTaskDao = new HistoryTaskDao(historyTaskDaoConfig, this);
        multiMediaDao = new MultiMediaDao(multiMediaDaoConfig, this);
        taskDao = new TaskDao(taskDaoConfig, this);
        wordDao = new WordDao(wordDaoConfig, this);

        registerDao(HistoryTask.class, historyTaskDao);
        registerDao(MultiMedia.class, multiMediaDao);
        registerDao(Task.class, taskDao);
        registerDao(Word.class, wordDao);
    }
    
    public void clear() {
        historyTaskDaoConfig.clearIdentityScope();
        multiMediaDaoConfig.clearIdentityScope();
        taskDaoConfig.clearIdentityScope();
        wordDaoConfig.clearIdentityScope();
    }

    public HistoryTaskDao getHistoryTaskDao() {
        return historyTaskDao;
    }

    public MultiMediaDao getMultiMediaDao() {
        return multiMediaDao;
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

    public WordDao getWordDao() {
        return wordDao;
    }

}
