package com.sh3h.localprovider.greendaoDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sh3h.localprovider.greendaoEntity.Word;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HL_WORD".
*/
public class WordDao extends AbstractDao<Word, Long> {

    public static final String TABLENAME = "HL_WORD";

    /**
     * Properties of entity Word.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ID = new Property(0, Long.class, "ID", true, "ID");
        public final static Property PARENT_ID = new Property(1, String.class, "PARENT_ID", false, "PARENT__ID");
        public final static Property GROUP = new Property(2, String.class, "GROUP", false, "GROUP");
        public final static Property NAME = new Property(3, String.class, "NAME", false, "NAME");
        public final static Property VALUE = new Property(4, String.class, "VALUE", false, "VALUE");
        public final static Property VALUE_EX = new Property(5, String.class, "VALUE_EX", false, "VALUE__EX");
        public final static Property REMARK = new Property(6, String.class, "REMARK", false, "REMARK");
        public final static Property EXTEND = new Property(7, String.class, "EXTEND", false, "EXTEND");
    }


    public WordDao(DaoConfig config) {
        super(config);
    }
    
    public WordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HL_WORD\" (" + //
                "\"ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: ID
                "\"PARENT__ID\" TEXT," + // 1: PARENT_ID
                "\"GROUP\" TEXT," + // 2: GROUP
                "\"NAME\" TEXT NOT NULL ," + // 3: NAME
                "\"VALUE\" TEXT NOT NULL ," + // 4: VALUE
                "\"VALUE__EX\" TEXT," + // 5: VALUE_EX
                "\"REMARK\" TEXT," + // 6: REMARK
                "\"EXTEND\" TEXT);"); // 7: EXTEND
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HL_WORD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Word entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
 
        String PARENT_ID = entity.getPARENT_ID();
        if (PARENT_ID != null) {
            stmt.bindString(2, PARENT_ID);
        }
 
        String GROUP = entity.getGROUP();
        if (GROUP != null) {
            stmt.bindString(3, GROUP);
        }
        stmt.bindString(4, entity.getNAME());
        stmt.bindString(5, entity.getVALUE());
 
        String VALUE_EX = entity.getVALUE_EX();
        if (VALUE_EX != null) {
            stmt.bindString(6, VALUE_EX);
        }
 
        String REMARK = entity.getREMARK();
        if (REMARK != null) {
            stmt.bindString(7, REMARK);
        }
 
        String EXTEND = entity.getEXTEND();
        if (EXTEND != null) {
            stmt.bindString(8, EXTEND);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Word entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
 
        String PARENT_ID = entity.getPARENT_ID();
        if (PARENT_ID != null) {
            stmt.bindString(2, PARENT_ID);
        }
 
        String GROUP = entity.getGROUP();
        if (GROUP != null) {
            stmt.bindString(3, GROUP);
        }
        stmt.bindString(4, entity.getNAME());
        stmt.bindString(5, entity.getVALUE());
 
        String VALUE_EX = entity.getVALUE_EX();
        if (VALUE_EX != null) {
            stmt.bindString(6, VALUE_EX);
        }
 
        String REMARK = entity.getREMARK();
        if (REMARK != null) {
            stmt.bindString(7, REMARK);
        }
 
        String EXTEND = entity.getEXTEND();
        if (EXTEND != null) {
            stmt.bindString(8, EXTEND);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Word readEntity(Cursor cursor, int offset) {
        Word entity = new Word( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // ID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // PARENT_ID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // GROUP
            cursor.getString(offset + 3), // NAME
            cursor.getString(offset + 4), // VALUE
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // VALUE_EX
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // REMARK
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // EXTEND
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Word entity, int offset) {
        entity.setID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPARENT_ID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setGROUP(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setNAME(cursor.getString(offset + 3));
        entity.setVALUE(cursor.getString(offset + 4));
        entity.setVALUE_EX(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setREMARK(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setEXTEND(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Word entity, long rowId) {
        entity.setID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Word entity) {
        if(entity != null) {
            return entity.getID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Word entity) {
        return entity.getID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
